CS-16095 Packages upgrade
Ksyos/koi pull request #21
Opened 2022-08-12 08:22 UTC by donnyysmit

2022-08-12 13:00 UTC, ccoenraad requested changes
Looks great overall!
Please also update `CHANGELOG.md` (it is currently outdated).
Ideally we should follow the format of <https://keepachangelog.com/en/1.0.0/>.

2022-08-12 13:46 UTC, ccoenraad commented on CHANGELOG.md
> +### Changed:
@donnyysmit nitpicking: Please remove `:`

2022-08-12 13:47 UTC, ccoenraad approved these changes

2022-08-12 14:57 UTC, MichielVanDoorn requested changes
In the Jira ticket it says:
- Update the minor-version of the @ksyos-package if there are any changes.

Now the question can be whether packages upgrades can be considered changes?
In 3.2.7 also only a package upgrade happened, so I think the answer is yes.

2022-08-15 08:06 UTC, donnyysmit commented
> In the Jira ticket it says:
> 
> * Update the minor-version of the @ksyos-package if there are any changes.
> 
> Now the question can be whether packages upgrades can be considered changes? In 3.2.7 also only a package upgrade happened, so I think the answer is yes.

Bumping the patch version while we have `^`  doesn't change anything though, because `^` makes sure you always get the latest of the version you're in

2022-08-16 12:22 UTC, MichielVanDoorn approved these changes
top

2022-08-16 13:28 UTC, merged